from .templates import (
    ASSESSMENT_COMPLETE_MESSAGE,
    ASSESSMENT_INTRO_MESSAGE,
    ASSESSMENT_TRANSITION_MESSAGE,
    ASSESSOR_FOLLOWUP_PROMPT,
    ASSESSOR_OPENING_PROMPT,
    ASSESSOR_SCORING_PROMPT,
    GAP_ANALYZER_PROMPT,
    PLAN_GENERATOR_PROMPT,
    SKILL_EXTRACTOR_PROMPT,
)
